FROM golang:alpine AS builder

RUN apk add --no-cache make git

WORKDIR /go/src/myapp.github.com

COPY . .

RUN GOOS=linux GOARCH=amd64 go build -o /main

FROM alpine

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /main .

EXPOSE 8080

CMD ["./main"]
